package de.ruu.app.jeeeraaah.frontend.ui.fx.task.view;

import de.ruu.lib.fx.FXUtil;
import de.ruu.lib.fx.comp.DefaultFXCView;
import de.ruu.lib.fx.comp.FXCApp;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import de.ruu.lib.fx.comp.FXCService;
import jakarta.annotation.PostConstruct;
import jakarta.inject.Inject;
import javafx.scene.Parent;
import javafx.stage.Stage;
import lombok.extern.slf4j.Slf4j;

import java.util.Optional;

/**
 * Java FX Component Application {@link TaskViewApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2024.09.27 16:54:05:953
 */
@Slf4j
public class TaskViewApp extends FXCApp
{
	@Inject private FXCAppStartedEvent.FXCAppStartedEventDispatcher eventDispatcherFXCAppStarted;

	@PostConstruct private void postConstruct()
	{
		eventDispatcherFXCAppStarted.add(e -> onAppStarted(e));
	}

	private void onAppStarted(FXCAppStartedEvent e)
	{
		if (optionalPrimaryView().isPresent())
		{
			DefaultFXCView<?, ?, ?> view = optionalPrimaryView().get();
			Parent                  root = view.localRoot();

			Optional<Stage> optionalStage = FXUtil.getStage(root);
			if (optionalStage.isPresent())
			{
				Stage stage = optionalStage.get();
				stage.setTitle("Task View");
			}
			else
			{
				log.warn("no stage found for the primary view: {}", view.getClass().getName());
			}
		}
		else
		{
			log.warn("no primary view found for application: {}", getClass().getName());
		}
	}
}