package de.ruu.app.jeeeraaah.client.fx.task.view.hierarchy.predecessor.add.super_sub_or_predecessor;

import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link ConfiguratorAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2025.08.14 09:59:47:270
 */
@Slf4j class ConfiguratorAppRunner extends FXCAppRunner
{
	public static void main(String[] args)
	{
		log.debug("starting {}" ,ConfiguratorAppRunner.class.getName());
		FXCAppRunner.run(ConfiguratorApp.class, args);
		log.debug("finished {}", ConfiguratorAppRunner.class.getName());
	}
}