package de.ruu.app.jeeeraaah.client.fx.task.view.hierarchy.predecessor.add.super_sub_or_predecessor;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link ConfiguratorApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2025.08.14 09:59:47:251
 */
public class ConfiguratorApp extends FXCApp
{
}