package de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.successor.add.super_sub_or_successor;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link Configurator}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2025.08.14 09:59:46:970
 */
public class Configurator
		extends
				DefaultFXCView
				<
						Configurator,
						ConfiguratorService,
						ConfiguratorController
				>
{ }