package de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.directneighbours;

import de.ruu.app.jeeeraaah.common.api.bean.TaskBean;
import de.ruu.lib.fx.comp.FXCService;
import javafx.scene.layout.HBox;
import lombok.NonNull;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2025.06.20 14:19:19:514
 */
public interface TaskDirectNeighbourSuperService extends FXCService
{
	/** Populate the view with the optional super task for given {@link TaskBean}. */
	void populateViewFor(@NonNull TaskBean taskBean);

	HBox hBox();
}