package de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.directneighbours;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link TaskWithDirectNeighbours}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2025.06.13 17:06:53:220
 */
public class TaskWithDirectNeighbours
		extends DefaultFXCView<TaskWithDirectNeighbours, TaskWithDirectNeighboursService, TaskWithDirectNeighboursController>
{
//	@Override public @NonNull TaskWithDirectNeighboursService service()
//	{
//		return (TaskWithDirectNeighboursService) super.service();
//	}
}