package de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.directneighbours;

import de.ruu.app.jeeeraaah.common.api.bean.TaskBean;
import de.ruu.lib.fx.comp.FXCController.DefaultFXCController;
import javafx.fxml.FXML;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.HBox;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2025.06.20 14:19:19:516
 */
class TaskDirectNeighbourSuperController
		extends DefaultFXCController<TaskDirectNeighbourSuper, TaskDirectNeighbourSuperService>
		implements TaskDirectNeighbourSuperService
{
	@FXML private AnchorPane root;
	@FXML private TextField  tfName;
	@FXML private HBox       hBox;

	@Override @FXML protected void initialize() { }

	@Override public void populateViewFor(TaskBean taskBean)
	{
		taskBean.superTask().ifPresentOrElse(t  -> tfName.setText(t.name()),
		                                     () -> tfName.setText(""));
	}

	@Override public HBox hBox()
	{
		return hBox;
	}
}