package de.ruu.app.jeeeraaah.frontend.ui.fx;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link Main}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2024.10.11 17:28:37:115
 */
public class Main extends DefaultFXCView<Main, MainService, MainController> { }