package de.ruu.app.jeeeraaah.client.fx.task.selector;

import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link TaskSelectorAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2025.08.14 09:59:47:270
 */
@Slf4j class TaskSelectorAppRunner extends FXCAppRunner
{
	public static void main(String[] args)
	{
		log.debug("starting {}", TaskSelectorAppRunner.class.getName());
		FXCAppRunner.run(TaskSelectorApp.class, args);
		log.debug("finished {}", TaskSelectorAppRunner.class.getName());
	}
}