package de.ruu.app.jeeeraaah.client.fx.task.view;

import de.ruu.app.jeeeraaah.common.fx.TaskFXBean;
import de.ruu.app.jeeeraaah.common.fx.TaskGroupFXBean;
import de.ruu.lib.fx.comp.FXCService;
import lombok.NonNull;

import java.util.Optional;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.09.27 16:54:05:943
 */
public interface TaskViewService extends FXCService
{
	@NonNull Optional<TaskFXBean> task();
	@NonNull TaskFXBean create(TaskGroupFXBean group);
	void populateViewFor(@NonNull TaskFXBean task);
	void setEditable(boolean editable);
}