package de.ruu.app.jeeeraaah.client.fx.task.view;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link TaskView}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2024.09.27 16:54:05:932
 */
public class TaskView extends DefaultFXCView<TaskView, TaskViewService, TaskViewController> { }