package de.ruu.app.jeeeraaah.client.fx.task.view;

import de.ruu.lib.fx.comp.FXCAppRunner;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link TaskViewAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.09.27 16:54:05:957
 */
@Slf4j
public class TaskViewAppRunner extends FXCAppRunner
{
	public static void main(String[] args) throws ClassNotFoundException
	{
		log.debug("starting {}", TaskViewAppRunner.class.getName());
		FXCAppStartedEvent      .addReadsUnnamedModule();
		FXCAppRunner.run(TaskViewApp.class, args);
		log.debug("finished {}", TaskViewAppRunner.class.getName());
	}
}