package de.ruu.app.jeeeraaah.client.fx.task.view;

/**
 * Java FX Component {@link TaskViewNarrow}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2024.09.27 16:54:05:932
 */
@TaskViewNarrowQualifier
public class TaskViewNarrow extends TaskView
{
	@Override protected String fxmlResourceName()    { return getClass().getSimpleName() + ".fxml"; }
	@Override protected String cssResourceName()     { return getClass().getSimpleName() + ".css";  }
	@Override protected String controllerClassName() { return TaskView.class.  getName() + "Controller";  }
}