package de.ruu.app.jeeeraaah.client.fx.dash;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link Dash}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2025.03.20 12:21:07:903
 */
public class Dash extends DefaultFXCView<Dash, DashService, DashController> { }