package de.ruu.app.jeeeraaah.client.fx.dash;

import de.ruu.lib.fx.comp.FXCAppRunner;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link DashAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2025.03.20 12:21:07:988
 */
@Slf4j
class DashAppRunner extends FXCAppRunner
{
	public static void main(String[] args) throws ClassNotFoundException
	{
		log.debug("starting {}", DashAppRunner.class.getName());
		FXCAppStartedEvent.addReadsUnnamedModule();
		DashAppRunner     .addReadsUnnamedModule();
		FXCAppRunner.run(DashApp.class, args);
		log.debug("finished {}", DashAppRunner.class.getName());
	}

	public static void addReadsUnnamedModule()
	{
		DashAppRunner
				.class
				.getModule()
				.addReads(DashAppRunner.class.getClassLoader().getUnnamedModule());
	}
}