package de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup;

import de.ruu.lib.fx.comp.FXCService;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.10.12 07:54:38:617
 */
public interface TaskGroupManagementService extends FXCService { }