package de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link TaskGroupManagementApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2024.10.12 07:54:38:621
 */
public class TaskGroupManagementApp extends FXCApp
{
}