package de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link TaskGroupManagement}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2024.10.12 07:54:38:615
 */
public class TaskGroupManagement
		extends DefaultFXCView<TaskGroupManagement, TaskGroupManagementService, TaskGroupManagementController> { }