package de.ruu.app.jeeeraaah.frontend.ui.fx.task.gantt;

import de.ruu.lib.fx.comp.FXCService;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.12.22 11:45:01:813
 */
public interface TaskTreeTableService extends FXCService
{
}