package de.ruu.app.jeeeraaah.frontend.ui.fx.task.selector;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link TaskSelectorApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2025.08.14 09:59:47:251
 */
public class TaskSelectorApp extends FXCApp { }