package de.ruu.app.jeeeraaah.frontend.ui.fx.task.selector;

import de.ruu.app.jeeeraaah.common.bean.TaskGroupBean;
import de.ruu.lib.fx.comp.FXCService;
import javafx.beans.property.ReadOnlyObjectProperty;
import lombok.NonNull;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2025.08.14 09:59:47:112
 */
public interface TaskSelectorService extends FXCService
{
	ReadOnlyObjectProperty<de.ruu.app.jeeeraaah.common.bean.TaskBean> selectionChangedProperty();

	void populateFor(@NonNull TaskGroupBean taskGroup);
}