package de.ruu.app.jeeeraaah.frontend.ui.fx.task.selector;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link TaskSelector}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2025.08.14 09:59:46:970
 */
public class TaskSelector
		extends
				DefaultFXCView
				<
						TaskSelector,
						TaskSelectorService,
						TaskSelectorController
				>
{ }