package de.ruu.app.jeeeraaah.client.fx.task.gantt;

import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link TaskTreeTableAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.12.22 11:45:01:848
 */
@Slf4j class TaskTreeTableAppRunner extends FXCAppRunner
{
	public static void main(String[] args)
	{
		log.debug("starting " + TaskTreeTableAppRunner.class.getName());
		FXCAppRunner.run(TaskTreeTableApp.class, args);
		log.debug("finished " + TaskTreeTableAppRunner.class.getName());
	}
}