package de.ruu.app.jeeeraaah.client.fx.task.gantt;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link TaskTreeTable}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2024.12.22 11:45:01:786
 */
public class TaskTreeTable extends DefaultFXCView<TaskTreeTable, TaskTreeTableService, TaskTreeTableController> { }