package de.ruu.app.jeeeraaah.client.fx.task.gantt;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link TaskTreeTableApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2024.12.22 11:45:01:845
 */
public class TaskTreeTableApp extends FXCApp
{
}