package de.ruu.app.jeeeraaah.client.fx.taskgroup;

import de.ruu.app.jeeeraaah.client.fx.MainAppRunner;
import de.ruu.lib.fx.comp.FXCAppRunner;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link TaskGroupManagementAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.10.12 07:54:38:623
 */
@Slf4j class TaskGroupManagementAppRunner extends FXCAppRunner
{
	public static void main(String[] args) throws ClassNotFoundException
	{
		log.debug("starting {}", TaskGroupManagementAppRunner.class.getName());
		FXCAppStartedEvent.addReadsUnnamedModule();
		FXCAppRunner.run(TaskGroupManagementApp.class, args);
		log.debug("finished {}", TaskGroupManagementAppRunner.class.getName());
	}
}