package de.ruu.app.jeeeraaah.frontend.ui.fx.task;

import de.ruu.lib.fx.comp.FXCService;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.12.27 15:31:28:922
 */
public interface TaskManagementService extends FXCService { }