package de.ruu.app.jeeeraaah.client.fx;

import de.ruu.lib.fx.comp.FXCService;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.10.11 17:28:37:117
 */
public interface MainService extends FXCService
{
}