package de.ruu.app.jeeeraaah.client.fx;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link MainApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2024.10.11 17:28:37:125
 */
public class MainApp extends FXCApp { }