package de.ruu.app.jeeeraaah.client.fx;

import de.ruu.app.jeeeraaah.client.fx.taskgroup.TaskGroupManagementDisposeRequestEvent;
import de.ruu.lib.fx.comp.FXCAppRunner;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link MainAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.10.11 17:28:37:127
 */
@Slf4j
public class MainAppRunner extends FXCAppRunner
{
	public static void main(String[] args) throws ClassNotFoundException
	{
		log.debug("starting {}", MainAppRunner.class.getName());
		FXCAppStartedEvent                    .addReadsUnnamedModule();
		TaskGroupManagementDisposeRequestEvent.addReadsUnnamedModule();
		FXCAppRunner.run(MainApp.class, args);
		log.debug("finished {}", MainAppRunner.class.getName());
	}
}