package de.ruu.app.jeeeraaah.frontend.ui.fx.task.edit;

import de.ruu.app.jeeeraaah.client.fx.task.view.TaskView;
import de.ruu.app.jeeeraaah.common.fx.TaskFXBean;
import de.ruu.app.jeeeraaah.common.fx.TaskGroupFXBean;
import de.ruu.lib.fx.FXUtil;
import de.ruu.lib.fx.comp.FXCController.DefaultFXCController;
import jakarta.inject.Inject;
import javafx.fxml.FXML;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;
import lombok.NonNull;

import java.util.Optional;

/**
 * Java FX Component View Controller
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewController} at 2024.10.06 11:23:46:768
 */
class TaskEditorController extends DefaultFXCController<TaskEditor, TaskEditorService>
		implements TaskEditorService
{
	@FXML private AnchorPane root;
	@FXML private VBox       vBxContainerEditor;

	@Inject private TaskView taskView;

	@Override
	@FXML protected void initialize()
	{
		FXUtil.setChildrenInTreeEditable(taskView.localRoot(), true);
		vBxContainerEditor.getChildren().add(taskView.localRoot());
	}

	@Override public @NonNull Optional<TaskFXBean> task()              { return taskView.service().task();        }
	@Override public @NonNull TaskFXBean create(TaskGroupFXBean group) { return taskView.service().create(group); }
	@Override public void task(@NonNull TaskFXBean task)               {        taskView.service().populateViewFor(task);    }
}