package de.ruu.app.jeeeraaah.frontend.ui.fx.task.edit;

import de.ruu.app.jeeeraaah.common.fx.TaskFXBean;
import de.ruu.app.jeeeraaah.common.fx.TaskGroupFXBean;
import de.ruu.lib.fx.comp.FXCService;
import lombok.NonNull;

import java.util.Optional;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.10.06 11:23:46:766
 */
public interface TaskEditorService extends FXCService
{
	@NonNull Optional<TaskFXBean> task();
	@NonNull TaskFXBean create(TaskGroupFXBean group);
	void task(@NonNull TaskFXBean task);
}