package de.ruu.app.jeeeraaah.frontend.ui.fx.task.edit;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link TaskEditor}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2024.10.06 11:23:46:765
 */
public class TaskEditor extends DefaultFXCView<TaskEditor, TaskEditorService, TaskEditorController> { }