package de.ruu.app.jeeeraaah.client.fx.task.view.hierarchy.supersub;

import de.ruu.app.jeeeraaah.client.fx.task.view.hierarchy.TaskHierarchyService;
import de.ruu.app.jeeeraaah.common.bean.TaskBean;
import javafx.beans.property.ReadOnlyObjectProperty;
import javafx.scene.control.TreeItem;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2025.06.03 12:49:45:374
 */
public interface TaskHierarchySuperSubTasksService extends TaskHierarchyService
{
	ReadOnlyObjectProperty<TreeItem<TaskBean>> selectedItem();
}