package de.ruu.app.jeeeraaah.client.fx.task.view.hierarchy.supersub;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link TaskHierarchySuperSubTasksApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2025.06.03 12:49:45:392
 */
public class TaskHierarchySuperSubTasksApp extends FXCApp { }