package de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link TaskHierarchyAbstract}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2025.06.03 12:49:45:230
 */
public abstract class TaskHierarchyAbstract
		extends DefaultFXCView<TaskHierarchyAbstract, TaskHierarchyService, TaskHierarchyControllerAbstract> { }