package de.ruu.app.jeeeraaah.client.fx.task.view.directneighbours;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link TaskDirectNeighbourSuper}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2025.06.20 14:19:19:353
 */
public class TaskDirectNeighbourSuper
		extends DefaultFXCView<TaskDirectNeighbourSuper, TaskDirectNeighbourSuperService, TaskDirectNeighbourSuperController>
{
//	@Override public @NonNull TaskDirectNeighbourSuperService service()
//	{
//		return (TaskDirectNeighbourSuperService) super.service();
//	}
}