package de.ruu.app.jeeeraaah.client.fx.task.view.directneighbours;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link TaskDirectNeighbourSuperApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2025.06.20 14:19:19:530
 */
public class TaskDirectNeighbourSuperApp extends FXCApp
{
}