package de.ruu.app.jeeeraaah.client.fx.task.view.directneighbours;

import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link TaskDirectNeighbourSuperAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2025.06.20 14:19:19:553
 */
@Slf4j class TaskDirectNeighbourSuperAppRunner extends FXCAppRunner
{
	public static void main(String[] args)
	{
		log.debug("starting TaskViewDirectNeighbourSuperAppRunner.class.getName()");
		FXCAppRunner.run(TaskDirectNeighbourSuperApp.class, args);
		log.debug("finished TaskViewDirectNeighbourSuperAppRunner.class.getName()");
	}
}