package de.ruu.app.jeeeraaah.client.fx.task.view.directneighbours;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link TaskWithDirectNeighboursApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2025.06.13 17:06:53:274
 */
public class TaskWithDirectNeighboursApp extends FXCApp
{
}