package de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup.edit;

import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link TaskGroupEditorRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.10.12 12:36:45:065
 */
@Slf4j class TaskGroupEditorRunner extends FXCAppRunner
{
	public static void main(String[] args)
	{
		log.debug("starting TaskGroupEditorRunner.class.getName()");
		FXCAppRunner.run(TaskGroupEditorApp.class, args);
		log.debug("finished TaskGroupEditorRunner.class.getName()");
	}
}