package de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup.edit;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link TaskGroupEditorApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2024.10.12 12:36:45:064
 */
public class TaskGroupEditorApp extends FXCApp
{
}