package de.ruu.app.jeeeraaah.frontend.ui.fx.taskgroup.edit;

import de.ruu.app.jeeeraaah.common.fx.TaskGroupFXBean;
import de.ruu.lib.fx.comp.FXCService;
import lombok.NonNull;

import java.util.Optional;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2024.10.12 12:36:45:058
 */
public interface TaskGroupEditorService extends FXCService
{
	Optional<TaskGroupFXBean> taskGroup();
	void taskGroup(@NonNull TaskGroupFXBean taskGroupFXBean);
}