package de.ruu.app.jeeeraaah.client.fx.task.view.hierarchy.successor;

import de.ruu.lib.fx.comp.FXCAppRunner;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link TaskHierarchySuccessorsAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2025.06.03 12:49:45:396
 */
@Slf4j class TaskHierarchySuccessorsAppRunner extends FXCAppRunner
{
	public static void main(String[] args)
	{
		log.debug("starting {}", TaskHierarchySuccessorsAppRunner.class.getName());
		FXCAppStartedEvent.addReadsUnnamedModule();
		FXCAppRunner.run(TaskHierarchySuccessorsApp.class, args);
		log.debug("finished {}", TaskHierarchySuccessorsAppRunner.class.getName());
	}
}