package de.ruu.app.jeeeraaah.client.fx.task.view.hierarchy.successor;

import de.ruu.app.jeeeraaah.client.fx.task.view.hierarchy.TaskHierarchyService;
import de.ruu.app.jeeeraaah.common.bean.TaskBean;
import javafx.scene.control.TreeItem;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2025.06.03 12:49:45:374
 */
public interface TaskHierarchySuccessorsService extends TaskHierarchyService
{
	void selectedSuperSubTaskTreeItemChanged(TreeItem<TaskBean> treeItem);
}