package de.ruu.app.jeeeraaah.client.fx.task;

import de.ruu.lib.fx.comp.FXCAppRunner;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link TaskManagementAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.12.27 15:31:28:952
 */
@Slf4j class TaskManagementAppRunner extends FXCAppRunner
{
	public static void main(String[] args) throws ClassNotFoundException
	{
		log.debug("starting {}", TaskManagementAppRunner.class.getName());
		FXCAppStartedEvent      .addReadsUnnamedModule();
		FXCAppRunner.run(TaskManagementApp.class, args);
		log.debug("finished {}", TaskManagementAppRunner.class.getName());
	}
}