package de.ruu.app.jeeeraaah.client.fx.task;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link TaskManagementApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2024.12.27 15:31:28:949
 */
public class TaskManagementApp extends FXCApp
{
}