package de.ruu.app.jeeeraaah.client.fx.task;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link TaskManagement}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2024.12.27 15:31:28:894
 */
public class TaskManagement extends DefaultFXCView<TaskManagement, TaskManagementService, TaskManagementController> { }