package de.ruu.app.jeeeraaah.frontend.ui.fx.dash;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link DashApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2025.03.20 12:21:07:981
 */
public class DashApp extends FXCApp { }