package de.ruu.app.jeeeraaah.frontend.ui.fx.dash;

import de.ruu.lib.fx.comp.FXCService;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2025.03.20 12:21:07:961
 */
public interface DashService extends FXCService { }