package de.ruu.app.jeeeraaah.client.fx.task.view.list.directneighbours;

import de.ruu.lib.fx.comp.DefaultFXCView;

/**
 * Java FX Component {@link TaskListDirectNeighbours}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2025.06.13 16:15:13:802
 */
public class TaskListDirectNeighbours
		extends DefaultFXCView<TaskListDirectNeighbours, TaskListDirectNeighboursService, TaskListDirectNeighboursController>
{
//	@Override public @NonNull TaskListDirectNeighboursService service()
//	{
//		return (TaskListDirectNeighboursService) super.service();
//	}
}