package de.ruu.app.jeeeraaah.client.fx.task.view.list.directneighbours;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link TaskListDirectNeighboursApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2025.06.13 16:15:13:867
 */
public class TaskListDirectNeighboursApp extends FXCApp
{
}