package de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.predecessor.add.super_sub_or_predecessor;

import de.ruu.app.jeeeraaah.common.api.bean.TaskBean;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.predecessor.add.ActionAdd.Context;
import de.ruu.lib.fx.comp.FXCService;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.experimental.Accessors;

import java.util.Optional;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2025.08.14 09:59:47:112
 */
public interface ConfiguratorService extends FXCService
{
	@RequiredArgsConstructor
	@Getter
	@Accessors(fluent = true)
	class ActionAddToSuperSubOrPredecessorConfigurationResult
	{
		private final TaskBean chosenPredecessorTaskBean;
		private final TaskBean targetTask;
	}

	void context(Context context);
	Optional<ActionAddToSuperSubOrPredecessorConfigurationResult> result();
}