package de.ruu.app.jeeeraaah.client.fx.taskgroup.selector;

import de.ruu.lib.fx.comp.DefaultFXCView;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component {@link TaskGroupSelector}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCView} at 2025.03.20 16:56:31:254
 */
@Slf4j
public class TaskGroupSelector extends DefaultFXCView<TaskGroupSelector, TaskGroupSelectorService, TaskGroupSelectorController> { }