package de.ruu.app.jeeeraaah.client.fx.taskgroup.selector;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link TaskGroupSelectorApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2025.03.20 16:56:31:327
 */
public class TaskGroupSelectorApp extends FXCApp { }