package de.ruu.app.jeeeraaah.client.fx.taskgroup.selector;

import de.ruu.lib.fx.comp.FXCAppRunner;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link TaskGroupSelectorAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2025.03.20 16:56:31:330
 */
@Slf4j class TaskGroupSelectorAppRunner extends FXCAppRunner
{
	public static void main(String[] args)
	{
		log.debug("starting TaskGroupSelectorAppRunner.class.getName()");
		FXCAppRunner.run(TaskGroupSelectorApp.class, args);
		log.debug("finished TaskGroupSelectorAppRunner.class.getName()");
	}
}