package de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.supersub;

import de.ruu.lib.fx.comp.FXCAppRunner;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link TaskHierarchySuperSubTasksAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2025.06.03 12:49:45:396
 */
@Slf4j class TaskHierarchySuperSubTasksAppRunner extends FXCAppRunner
{
	public static void main(String[] args)
	{
		log.debug("starting {}", TaskHierarchySuperSubTasksAppRunner.class.getName());
		FXCAppStartedEvent.addReadsUnnamedModule();
		FXCAppRunner.run(TaskHierarchySuperSubTasksApp.class, args);
		log.debug("finished {}", TaskHierarchySuperSubTasksAppRunner.class.getName());
	}
}