package de.ruu.app.jeeeraaah.client.fx.task.edit;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link TaskEditorApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2024.10.06 11:23:46:771
 */
public class TaskEditorApp extends FXCApp { }