package de.ruu.app.jeeeraaah.client.fx.task.edit;

import de.ruu.lib.fx.comp.FXCAppRunner;
import de.ruu.lib.fx.comp.FXCAppStartedEvent;
import lombok.extern.slf4j.Slf4j;

/**
 * Java FX Component Application Runner {@link TaskEditorAppRunner}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCAppRunner} at 2024.10.06 11:23:46:773
 */
@Slf4j class TaskEditorAppRunner extends FXCAppRunner
{
	public static void main(String[] args) throws ClassNotFoundException
	{
		log.debug("starting {}", TaskEditorAppRunner.class.getName());
		FXCAppStartedEvent.addReadsUnnamedModule();
		FXCAppRunner.run(TaskEditorApp.class, args);
		log.debug("finished {}", TaskEditorAppRunner.class.getName());
	}
}