package de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.predecessor;

import de.ruu.lib.fx.comp.FXCApp;

/**
 * Java FX Component Application {@link TaskHierarchyPredecessorsApp}
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCApp} at 2025.06.03 12:49:45:392
 */
public class TaskHierarchyPredecessorsApp extends FXCApp { }