package de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.predecessor;

import de.ruu.app.jeeeraaah.common.api.bean.TaskBean;
import de.ruu.app.jeeeraaah.frontend.ui.fx.task.view.hierarchy.TaskHierarchyService;
import javafx.scene.control.TreeItem;

/**
 * Java FX Component View Service
 * <p>
 * generated by {@code de.ruu.lib.gen.java.fx.comp.GeneratorFXCViewService} at 2025.06.03 12:49:45:374
 */
public interface TaskHierarchyPredecessorsService extends TaskHierarchyService
{
	void selectedSuperSubTaskTreeItemChanged(TreeItem<TaskBean> treeItem);
}