name: build module r-uu/mvn-control with maven triggered manually

on:
  workflow_dispatch:   # runs on manual trigger
    inputs:
      module:
        description: 'module r-uu/mvn-control'
        required: true
        default: 'r-uu/mvn-control'
      skipTests:
        description: 'skip tests?'
        required: false
        default: 'false'
  push:
    branches: ["**"]   # runs on every push to any branch
  pull_request:        # runs on every PR to any branch
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.module }}
    steps:
      - uses: actions/checkout@v4
      - name: set up java 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'graalvm'
      - name: build with maven
        working-directory: ${{ inputs.module }}
        run: |
          if [[ "${{ inputs.skipTests }}" == "true" ]]; then
            mvn clean install -DskipTests
          else
            mvn clean install
          fi
