name: clean install complete codespace (all modules) on push or pull request

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
    inputs:
      skipTests:
        description: 'Skip running tests'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 24 (adjust if you want another version)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24
          cache: maven

      # Build all modules starting from the root pom
      - name: Build with Maven
        working-directory: r-uu
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.skipTests }}" == "true" ]]; then
            mvn -B clean install -DskipTests
          else
            mvn -B clean install
          fi
